// books
export const FETCH_BOOK_LOADING = 'FETCH_BOOK_LOADING';
export const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS';
export const FETCH_BOOK_ERROR = 'FETCH_BOOK_ERROR';
export const BOOK_SEARCH_KEY_WORDS_CHANGE = 'BOOK_SEARCH_KEY_WORDS_CHANGE';

// bookDetail
export const FETCH_BOOK_DATAIL_LOADING = 'FETCH_BOOK_DATAIL_LOADING';
export const FETCH_BOOK_DATAIL_SUCCESS = 'FETCH_BOOK_DATAIL_SUCCESS';
export const FETCH_BOOK_DATAIL_ERROR = 'FETCH_BOOK_DATAIL_ERROR';

//movie
export const FETCH_MOVIE_LOADING = 'FETCH_MOVIE_LOADING';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR';
export const MOVIE_SEARCH_KEY_WORDS_CHANGE = 'MOVIE_SEARCH_KEY_WORDS_CHANGE';

// movieDetail
export const FETCH_MOVIE_DATAIL_LOADING = 'FETCH_MOVIE_DATAIL_LOADING';
export const FETCH_MOVIE_DATAIL_SUCCESS = 'FETCH_MOVIE_DATAIL_SUCCESS';
export const FETCH_MOVIE_DATAIL_ERROR = 'FETCH_MOVIE_DATAIL_ERROR';
